version: "3.3"

services:
  proto:
    image: grpc-chat-proto
    build:
      context: .
      dockerfile: ./proto/Dockerfile
    command: make proto
    restart: "no"
    volumes:
      - ./proto:/grpc-chat/proto
      - ./Makefile:/grpc-chat/Makefile

  server:
    image: golang:1.16-stretch
    working_dir: /go/src/github.com/car12o/grpc-chat
    command: make dev
    restart: unless-stopped
    depends_on:
      - proto
    ports:
      - "3000:3000"
    volumes:
      - .:/go/src/github.com/car12o/grpc-chat

